# -*- coding: utf-8 -*-
"""TP final modulo 2 (brenda cendra) - .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWq70jAnFb9iUaZFDr21vWoFfuloT3qF

## **Ejercicio 1**
"""

def cuadrante (x,y):
  if (x > 0 and y > 0):
    print("El punto se encuentra en el 1er cuadrante.")
  elif (x < 0 and y > 0):
    print("El punto se encuentra en el 2do cuadrante.")
  elif (x < 0 and y < 0):
    print("El punto se encuenta en el 3er cuadrante.")
  elif (x > 0 and y < 0):
    print("El punto se encuentra en el 4to cuadrante.")
  elif (x == 0 and y != 0):
    print("El punto se encuentra sobre el eje Y con valores","positivos." if (y > 0) else "negativos.") # Lo puse para verificar en que parte del eje Y esta
  elif(x != 0 and y == 0):
    print("El punto se encuentra sobre el eje Y con valores","positivos." if (x > 0) else "negativos.")
  else:
    print("El punto se encuentra en el centro.")

cuadrante(0,3)

"""## **Ejercicio 2**"""

import random

lista1 = [random.randrange(1,100) for lista1 in range(5)]
lista2 = [random.randrange(1,100) for lista2 in range(5)]
lista3 = [random.randrange(1,100) for lista3 in range(5)]

maximo = max(max(lista1),max(lista2),max(lista3))

minimo = min(min(lista1),min(lista2),min(lista3))

print("Lista 1:",lista1)
print("Lista 2:", lista2)
print("Lista 3:", lista3)
print("Mayor valor entre las tres listas: {}".format(maximo))
print("Menor valor de cada lista: {}".format(minimo))

"""## **Ejercicio 3**"""

def palindromos(lista_palabras):
    palindromo_lista = []
    for palabra in lista_palabras:
        palabra = palabra.lower()
        if palabra == palabra[::-1]:
            palindromo_lista.append(palabra)
    return palindromo_lista

lista_palabras = ["Anilina", "Reconocer", "Salas", "Oso", "Hola", "Python"]
resultado = palindromos(lista_palabras)
print("Palíndromos en la lista:", resultado)